export const company = {
  name: "Grow Bridge",
  email: "abhay@growbridge.org",
  phone: "+91 84878 28752",
  whatsapp: "918487828752",
  location: "Ahmedabad, Gujarat, India",
  tagline: "Where Business Growth Begins",
  description:
    "Comprehensive support for startups and MSMEs with registration, certification, funding, and business growth services.",
};

export const serviceGroups = [
  {
    title: "MSME & Startup Funding Support",
    image: "/government_grants_hero_premium_1769686253475.png",
    href: "/funding",
    benefit: "Collateral-free Loans",
    timeline: "30-45 Days",
    items: [
      "MSME Loans up to ₹5 Cr",
      "Startup Seed Fund Support",
      "CGTMSE & MUDRA Loans",
      "PMEGP Subsidies",
      "Collateral-free Loan Guidance",
      "Startup India Seed Fund",
    ],
  },
  {
    title: "Business Registration",
    image: "/business_registration_hero_premium_1769686804174.png",
    href: "/services/business-registration",
    benefit: "100% Compliance",
    timeline: "7-10 Days",
    items: [
      "Pvt Ltd, LLP, OPC Registration",
      "MSME Udyam & GST Registration",
      "Startup India Certification",
      "NGO Darpan Registration",
      "Section 8 Company",
      "GeM Registration",
    ],
  },
  {
    title: "Certifications & IP",
    image: "/certifications_hero_image_premium_1769686077900.png",
    href: "/services/certifications",
    benefit: "Enhanced Credibility",
    timeline: "15-45 Days",
    items: [
      "ISO 9001, 14001, 45001",
      "FSSAI, IEC & Trade License",
      "ZED & MSME Certifications",
      "BIS Certification",
      "Trademark Registration",
      "Patent Filing",
    ],
  },
  {
    title: "Growth Strategy",
    image: "/growth_strategy_hero_premium_1769686968239.png",
    href: "/services/growth-strategy",
    benefit: "Measurable Results",
    timeline: "Custom",
    items: [
      "Digital Marketing & SEO",
      "Brand Identity & Positioning",
      "Market Expansion Analysis",
      "Detailed Project Report (DPR)",
      "Investor Pitch Decks",
      "Techno-Economic Viability (TEV)",
    ],
  },
  {
    title: "Tax & Compliance",
    image: "/business_registration_hero_premium_1769686804174.png",
    href: "/services/tax-exemption-benefits",
    benefit: "Tax Optimization",
    timeline: "Monthly/Annual",
    items: [
      "GST Filing & Compliance",
      "Income Tax & TDS Returns",
      "Startup Tax Exemption (80-IAC)",
      "12A & 80G Registrations",
      "Tax Planning & Advisory",
      "Annual Compliance Filing",
    ],
  },
  {
    title: "Legal Services",
    image: "/legal_consultancy_hero_premium_1769687115697.png",
    href: "/services/legal",
    benefit: "Risk Mitigation",
    timeline: "Ongoing",
    items: [
      "Partnership & Vendor Agreements",
      "Trademark & IP Registration",
      "ROC & Annual Compliance",
      "Contract Drafting & Review",
      "Compliance Audit",
      "Corporate Legal Advisory",
    ],
  },
  {
    title: "Marketing & Branding",
    image: "/marketing_branding_hero_premium_1769687063274.png",
    href: "/services/marketing",
    benefit: "Measurable Results",
    timeline: "Custom",
    items: [
      "Performance Marketing",
      "Social Media Management",
      "Brand Architecture",
      "Website Development",
      "Content Marketing",
      "SEO & SEM Campaigns",
    ],
  },
  {
    title: "CIBIL Assistance",
    image: "/business_loans_hero_premium_1769686161627.png",
    href: "/services/cibil-assistance",
    benefit: "Better Loan Eligibility",
    timeline: "45-90 Days",
    items: [
      "CIBIL Error Correction",
      "Negative Remarks Removal",
      "CCR Ranking Enhancement",
      "Credit Score Improvement",
      "Dispute Resolution",
      "Loan Eligibility Optimization",
    ],
  },
];

export const fundingContent = {
  introTitle: "Funding & Government Schemes",
  introBody:
    "We assess eligibility, prepare documentation, and guide applications for suitable government-aligned programs and financing options. Our focus is building a compliant, compelling profile that improves approvals and timelines.",
  bullets: [
    "Eligibility mapping by stage and sector",
    "Compliant documentation and dossier preparation",
    "Application filing and tracking support",
    "Funding-readiness advisory for faster responses",
  ],
};
